name: "SmartBeans"
description: "Write smart home automations in Java - for Home Assistant"
image: "beanssmart/addon-smartbeans-{arch}"
version: "1.0.0-beta-1"
slug: "smartbeans"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
