name: "SmartBeans"
description: "Write smart home automations in Java - for Home Assistant"
image: "tobibo82/addon-smartbeans-{arch}"
version: "0.0.1"
slug: "smartbeans"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
